[package]
name = "adp-sdk"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
zip = "0.6"
tar = "0.4"
walkdir = "2"
sha2 = "0.10"
hex = "0.4"
tempfile = { version = "3", optional = false }
